import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'

export default function FirstPost() {
    return(
    <div className={styles.container}>
      <Head>
        <title>First Post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    <h1>First Post</h1>
    <h1>
        <Link href="/">
            <a className={styles.navigate}>Back to home!</a>
        </Link>
    </h1>
    </div>
    )
}